name: Build Gateway Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: lein modules install
    - name: Test
      run: lein modules test
